get vcs ref from latest image
openshift-assisted/assisted-installer-deployment pull request #197
Opened 2022-03-08 11:14 UTC by rccrdpccl

This change aims to eliminate possibility of race conditions on pushing images to quay.io and calculating the latest vcs ref available.

Instead of fetching the latest ref from HEAD through git, and then checking if the image is ready, we will get the latest image, and extract the ref from docker labels.
In case one repo has multiple images, we will take the reference in case it is the same on all images. In case they do differ, we will get the first image created, which is likely to have the oldest ref (thus common to all images).

The above it's not necessarily true, as it might be the case that a more recent reference took longer to push. However this scenario seems highly unlikely.

NOTE: this script is used in other parts of the CI:
https://github.com/openshift/release/blob/master/ci-operator/config/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master.yaml#L77
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master-presubmits.yaml#L216

It looks like those steps might also benefit from the same change, however if it's not so please let me know so we can change this PR accordingly.

2022-03-08 11:14 UTC, rccrdpccl commented
cc @michaellevy101 @osherdp

2022-03-08 13:48 UTC, osherdp requested changes

2022-03-08 13:48 UTC, osherdp commented on Dockerfile.assisted-installer-deployment
> +    skopeo \
seems like we already install it on line 13

2022-03-08 13:48 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        docker_uri = "docker://" + img + ":latest"
```suggestion
        docker_uri = f"docker://{img}:latest"
```

2022-03-08 13:48 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        json_out = output.stdout.decode("utf-8")
```suggestion
        output = subprocess.check_output(["skopeo", "inspect", docker_uri])
        json_out = output.decode("utf-8")
```

2022-03-08 13:48 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +    # if they differ, let's return the oldest one, as it is likely to be common
removing it will yield the same results, no?
```suggestion
```

2022-03-13 11:22 UTC, osherdp requested changes

2022-03-13 11:22 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        raise IndexError("No lists provided. Cannot find common element")
Seems to be more relevant in this case:
```suggestion
        raise ValueError("No lists provided. Cannot find common element")
```

2022-03-13 11:22 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +    raise RuntimeError("Could not find common element")
it seems more right to return ``None`` in this case:
```suggestion
    return None
```

2022-03-13 11:22 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +    sk = skopeo.Skopeo()
can we change all names here to not include abbrev?
e.g. ``sk->skeopeo_client``, ``img->image``
it will make code more English-like

2022-03-13 11:22 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        image_tags.append(sk.get_image_tags_by_pattern(img, tag_pattern))
```suggestion
    image_tags = [sk.get_image_tags_by_pattern(img, tag_pattern)
                  for img in images]
```

2022-03-13 11:22 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +            sys.exit(1)
seems to be equivalent to just not ``try-excepting`` and letting it fail for this exception

2022-03-13 11:22 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +    if len(image_tags) < 1:
I think it's more explicit to do:
```suggestion
    if len(image_tags) == 0:
```

2022-03-13 11:22 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        tag = image_tags[0][0]
redundant, no?
I means, seems like removal of those lines will yield the same results
```suggestion
```

2022-03-13 11:22 UTC, osherdp commented on tools/skopeo.py
> +class Skopeo:
Great idea to have this kind of abstraction :+1:

2022-03-14 09:03 UTC, rccrdpccl commented on tools/update_assisted_installer_yaml.py
> +        if in_all_lists(el, lists[1:]):
Thanks for the great feedback :wink:

2022-03-14 13:07 UTC, osherdp requested changes
just some small edits and we're ready

2022-03-14 13:07 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +    return True
this seems redundant now:
```suggestion
```

2022-03-14 13:07 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        raise ValueError(f"Couild not find common tag for images {images}")
nit: append blank line

2022-03-14 13:07 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        raise IndexError(f"Could not find any tags matching pattern `{tag_pattern}` for images `{images}`")
nit: append blank line

2022-03-14 13:07 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +        raise ValueError("No lists provided. Cannot find common element")
nit: append blank line

2022-03-14 13:07 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +            return el
nit: append blank line

2022-03-14 13:07 UTC, osherdp commented on tools/update_assisted_installer_yaml.py
> +    image_tags = []
you can delete it:
```suggestion
```

2022-03-14 15:47 UTC, osherdp commented
/hold
(just checking dry-run execution)

2022-03-14 15:48 UTC, osherdp commented
/unhold
yep, looks magnificent 
thank you @rccrdpccl!

2022-03-14 15:50 UTC, merged