MGMT-8890: Support -multi stream for OCP releases
openshift-assisted/assisted-installer-deployment pull request #293
Opened 2022-08-23 16:08 UTC by mkowalski

Contributes-to: MGMT-8890
Closes: MGMT-11553

/cc @osherdp

2022-08-23 16:09 UTC, mkowalski commented
Sample run gave me the following

```
INFO       bump_ocp_releases.py:290 New latest ocp release available for 4.11, 4.11.0 -> 4.11.1
INFO       bump_ocp_releases.py:200 Getting all releases for version 4.8 and architecture x86_64
INFO       bump_ocp_releases.py:200 Getting all releases for version 4.9 and architecture x86_64
INFO       bump_ocp_releases.py:200 Getting all releases for version 4.10 and architecture x86_64
INFO       bump_ocp_releases.py:200 Getting all releases for version 4.10 and architecture arm64
INFO       bump_ocp_releases.py:200 Getting all releases for version 4.11 and architecture x86_64
INFO       bump_ocp_releases.py:200 Getting all releases for version 4.11 and architecture arm64
INFO       sh.py:670 <Command '/usr/bin/make generate-configuration', pid 2962796>: process started
INFO       sh.py:670 <Command '/usr/bin/make generate-bundle', pid 2962893>: process started

[...]

-  value: '[{"openshift_version":"4.8","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.8.47-x86_64","version":"4.8.47"},{"openshift_version":"4.9","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.9.46-x86_64","version":"4.9.46"},{"openshift_version":"4.10","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-x86_64","version":"4.10.26"},{"openshift_version":"4.10","cpu_architecture":"arm64","cpu_architectures":["arm64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-aarch64","version":"4.10.26"},{"openshift_version":"4.11","cpu_architecture":"multi","cpu_architectures":["x86_64","arm64","ppc64le","s390x"],"url":"quay.io/openshift-release-dev/ocp-release:4.11.0-multi","version":"4.11.0","default":true}]' # release images
+  value: '[{"openshift_version":"4.8","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.8.47-x86_64","version":"4.8.47"},{"openshift_version":"4.9","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.9.46-x86_64","version":"4.9.46"},{"openshift_version":"4.10","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-x86_64","version":"4.10.26"},{"openshift_version":"4.10","cpu_architecture":"arm64","cpu_architectures":["arm64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-aarch64","version":"4.10.26"},{"openshift_version":"4.11","cpu_architecture":"multi","cpu_architectures":["x86_64","arm64","ppc64le","s390x"],"url":"quay.io/openshift-release-dev/ocp-release:4.11.1-multi","version":"4.11.1","default":true}]' # release images
```

2022-08-24 07:05 UTC, osherdp commented
> Sample run gave me the following
> 
> ```
> INFO       bump_ocp_releases.py:290 New latest ocp release available for 4.11, 4.11.0 -> 4.11.1
> INFO       bump_ocp_releases.py:200 Getting all releases for version 4.8 and architecture x86_64
> INFO       bump_ocp_releases.py:200 Getting all releases for version 4.9 and architecture x86_64
> INFO       bump_ocp_releases.py:200 Getting all releases for version 4.10 and architecture x86_64
> INFO       bump_ocp_releases.py:200 Getting all releases for version 4.10 and architecture arm64
> INFO       bump_ocp_releases.py:200 Getting all releases for version 4.11 and architecture x86_64
> INFO       bump_ocp_releases.py:200 Getting all releases for version 4.11 and architecture arm64
> INFO       sh.py:670 <Command '/usr/bin/make generate-configuration', pid 2962796>: process started
> INFO       sh.py:670 <Command '/usr/bin/make generate-bundle', pid 2962893>: process started
> 
> [...]
> 
> -  value: '[{"openshift_version":"4.8","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.8.47-x86_64","version":"4.8.47"},{"openshift_version":"4.9","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.9.46-x86_64","version":"4.9.46"},{"openshift_version":"4.10","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-x86_64","version":"4.10.26"},{"openshift_version":"4.10","cpu_architecture":"arm64","cpu_architectures":["arm64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-aarch64","version":"4.10.26"},{"openshift_version":"4.11","cpu_architecture":"multi","cpu_architectures":["x86_64","arm64","ppc64le","s390x"],"url":"quay.io/openshift-release-dev/ocp-release:4.11.0-multi","version":"4.11.0","default":true}]' # release images
> +  value: '[{"openshift_version":"4.8","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.8.47-x86_64","version":"4.8.47"},{"openshift_version":"4.9","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.9.46-x86_64","version":"4.9.46"},{"openshift_version":"4.10","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-x86_64","version":"4.10.26"},{"openshift_version":"4.10","cpu_architecture":"arm64","cpu_architectures":["arm64"],"url":"quay.io/openshift-release-dev/ocp-release:4.10.26-aarch64","version":"4.10.26"},{"openshift_version":"4.11","cpu_architecture":"multi","cpu_architectures":["x86_64","arm64","ppc64le","s390x"],"url":"quay.io/openshift-release-dev/ocp-release:4.11.1-multi","version":"4.11.1","default":true}]' # release images
> ```

You can also see the result in the dry-run job: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-assisted_assisted-installer-deployment/293/pull-ci-openshift-assisted-assisted-installer-deployment-master-bump-ocp-dry-run/1562109633315737600/artifacts/bump-ocp-dry-run/assisted-tools-bump-ocp/build-log.txt

2022-08-24 07:12 UTC, osherdp requested changes

2022-08-24 07:12 UTC, osherdp commented on tools/bump_ocp_releases.py
> +    r"curl https://multi.ocp.releases.ci.openshift.org/graph"
let's transform this to usage of ``requests``, I think it's the more Pythonic way rather than transferring the job to some OS command

2022-08-24 07:12 UTC, osherdp commented on tools/bump_ocp_releases.py
> +    r"curl https://multi.ocp.releases.ci.openshift.org/graph"
same goes with the ``jq`` part, ``response.json()`` can help you with getting the relevant dictionary with all the data

2022-08-24 07:12 UTC, osherdp commented on tools/bump_ocp_releases.py
> +    return list(release_data)
```suggestion
    return [r for r in release_data if minor_release in r["version"] and "nightly" not in r["version"]]
```

2022-09-20 10:45 UTC, mkowalski commented
/hold

In 4.12 there will be the same upgrade graph for single- and multi-arch release image. Not sure this here will be ever needed because we roll on 4.11-multi only as a temporary solution

2022-09-21 13:18 UTC, mkowalski commented
/close

2022-09-21 13:18 UTC, closed without merging