Extra validation checking if ticket was opened per logs
openshift-assisted/assisted-installer-deployment pull request #83
Opened 2021-05-11 09:40 UTC by oshercc

2021-05-11 12:25 UTC, osherdp requested changes

2021-05-11 12:25 UTC, osherdp commented on tools/create_triage_tickets.py
> +                                                                             "handheld")
```suggestion
    parser.add_argument("--mark-root", default=None, required=False, 
                        help="Location of the logs for marking as handheld")
```

2021-05-11 12:25 UTC, osherdp commented on tools/create_triage_tickets.py
> +                                                                             "handheld")
*handled

2021-05-11 12:25 UTC, osherdp commented on tools/create_triage_tickets.py
> +
delete

2021-05-11 12:25 UTC, osherdp commented on tools/create_triage_tickets.py
> +        logger.info(f"Marking {failure_id} as handled due, fount summary {summary}")
typo, and reformat sentence as it's not clear imho

2021-05-11 12:25 UTC, osherdp commented on tools/create_triage_tickets.py
> +    logger.info(f"Item {existing_tickets} looks new")
```suggestion
    logger.info(f"Item {summary} looks new")
```

2021-05-11 12:27 UTC, osherdp requested changes

2021-05-11 12:27 UTC, osherdp commented on tools/create_triage_tickets.py
> +    parser.add_argument("--mark-root", default=None, required=False, help="Location of the logs for marking as "
not sure about the name, but also I don't have any other suggestion than ``mark-root``
@YuviGold wdyt?

2021-05-11 15:07 UTC, omertuc commented on tools/create_triage_tickets.py
> +
After creating ticket should call mark_as_handled

2021-08-22 07:28 UTC, YuviGold commented
@oshercc is this PR still relevant? Please add a description to the PR if it is.

2021-08-31 09:58 UTC, closed without merging