MGMT-5241 - Remove 4.8 single override from version bump script
openshift-assisted/assisted-installer-deployment pull request #90
Opened 2021-05-26 17:55 UTC by djzager

It is no longer required because 4.8 is already part of the default versions JSON
as of this PR https://github.com/openshift/assisted-service/pull/1518

2021-05-26 17:55 UTC, djzager commented
This takes over #69

2021-05-26 19:11 UTC, djzager commented
cc @oshercc

2021-05-27 12:34 UTC, flaper87 requested changes

2021-05-27 12:34 UTC, flaper87 commented on tools/update_default_release_versions_to_latest.py
>          unhold_pr(github_pr)
perhaps this should happen at the bottom, once all of the other steps succeed.

(GH comments are dumb)

2021-05-27 13:00 UTC, flaper87 approved these changes
:pizza:

2021-05-27 13:11 UTC, osherdp requested changes

2021-05-27 13:11 UTC, osherdp commented on tools/update_default_release_versions_to_latest.py
> +        raise NoChangesNeeded
maybe I miss something
but why not just return?

2021-05-27 13:11 UTC, osherdp commented on tools/update_default_release_versions_to_latest.py
> +
delete blank line

2021-05-27 13:18 UTC, osherdp approved these changes

2021-05-27 13:18 UTC, merged